exclude: 'seed.py'
exclude: 'console.py'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.10.1  # Use the specific version you want
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Use the specific version you want
    hooks:
    -   id: isort
        args: ["--profile", "black"]  # This makes isort compatible with black

-   repo: https://github.com/myint/autoflake
    rev: v2.2.1  # Use the specific version you want
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-unused-variables', '--remove-all-unused-imports']

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the specific version you want
    hooks:
    -   id: flake8
