version: '3.8'

services:
  generic-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: generic-worker
    env_file: ./.env  # Contains WORKER_ID
    ports:
      - "80:8000"
    # The Dockerfile ENTRYPOINT calls deploy.sh, so no need for an extra 'command' here
    restart: unless-stopped

networks:
  default:
    driver: bridge
