services:
  worker-runner:
    build: .
    environment:
      - WORKER_ID=${WORKER_ID}
      - WORKER_REPO_URL=${WORKER_REPO_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
    ports:
      - "8080:8080"
    volumes:
      - pip-cache:/app/.cache/pip
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pip-cache:
